"use client";

import Link from "next/link";
import { useEffect, useState, type CSSProperties } from "react";
import { normalizeSiteConfig, type SiteConfig } from "../lib/site-config";
import { localizeSiteConfig, type Locale, ui } from "../lib/i18n";
import LanguageToggle from "./LanguageToggle";
import "./theme-overrides.css";
import "./hero-fix.css";
import "./cv-overrides.css";

export default function HomeClient({ initialSite, initialLocale = "en" }: { initialSite: SiteConfig; initialLocale?: Locale }) {
  const [site, setSite] = useState<SiteConfig>(initialSite);
  const [locale, setLocale] = useState<Locale>(initialLocale);
  useEffect(() => { let active = true; fetch("/api/site").then(response => response.ok ? response.json() : null).then(data => { if (active && data) setSite(normalizeSiteConfig(data)); }).catch(() => undefined); return () => { active = false; }; }, []);
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const display = localizeSiteConfig(site, locale);
  const labels = ui[locale];
  const [firstName, ...lastName] = display.name.trim().split(/\s+/);
  const theme = { "--purple": display.accent, "--ink": display.background, "--text": display.textColor, "--muted": display.mutedColor, "--site-font": display.typography.bodyFont, "--heading-font": display.typography.headingFont, "--heading-weight": display.typography.headingWeight, "--heading-style": display.typography.headingStyle, "--hero-title-color": display.typography.heroTitleColor, "--hero-title-size": `${display.typography.heroTitleSize}px`, "--section-title-color": display.typography.sectionTitleColor, "--section-title-size": `${display.typography.sectionTitleSize}px`, "--nav-text-color": display.typography.navColor, "--nav-font-size": `${display.typography.navSize}px`, "--body-font-size": `${display.typography.bodySize}px` } as CSSProperties;
  const sectionStyle = (section: "hero" | "projects" | "features" | "contact", order: number) => { const offsets = { hero: [0, 0], projects: [display.layout.projectsX, display.layout.projectsY], features: [display.layout.featuresX, display.layout.featuresY], contact: [display.layout.contactX, display.layout.contactY] } as const; return { order, transform: `translate(${offsets[section][0]}px, ${offsets[section][1]}px)` }; };
  return <main className="portfolio" style={theme}>
    <header className="topbar" style={{ justifyContent: display.layout.headerAlign, "--nav-gap": `${display.layout.headerGap}px` } as CSSProperties}><Link className="wordmark" href="/" style={{ transform: `translate(${display.layout.headerBrandX}px, ${display.layout.headerBrandY}px)` }}>{display.name}</Link><nav aria-label={labels.mainNavigation} style={{ transform: `translate(${display.layout.headerNavX}px, ${display.layout.headerNavY}px)` }}>{display.navItems.map(item => <Link key={`${item.label}-${item.href}`} href={item.href}>{item.label}</Link>)}</nav><LanguageToggle locale={locale} onChange={setLocale} /></header>
    <section id="home" className="hero-new" style={sectionStyle("hero", 1)}><div className="hero-copy-new" style={{ transform: `translate(${display.layout.heroCopyX}px, ${display.layout.heroCopyY}px)` }}><p className="hello">{display.greeting}</p><h1>{firstName} <span>{lastName.join(" ")}</span></h1><p className="roles">{display.tagline}</p><p className="hero-desc">{display.bio}</p><div className="hero-ctas"><a className="purple-button" href="#projects">{display.detailHeadings.projects.kicker} <b>→</b></a><Link className="outline-button" href="/iletisim">{labels.contactMe} <b>✉</b></Link></div><p className="tech-label">{labels.developingAreas}</p><div className="mini-tech">{display.skills.slice(0, 9).map(item => <span key={item}>{item}</span>)}</div></div><div className="hero-person" style={{ transform: `translate(${display.layout.heroPortraitX}px, ${display.layout.heroPortraitY}px)` }} aria-label={`${display.name} portrait`}><img src={display.heroImage} alt={display.name} /></div></section>
    <section id="projects" className="projects-section home-projects" style={sectionStyle("projects", 2)}><div className="section-title-row"><h2>{display.detailHeadings.projects.kicker}</h2><Link href="/my-projects">{display.detailHeadings.projects.title} <b>→</b></Link></div><div className="project-grid">{display.projects.map((project, index) => <article className="project-card" key={`home-project-${index}`}><div className="project-media">{project.imageUrl ? <img src={project.imageUrl} alt={`${project.title} proje görseli`} /> : <div className={`project-shot ${project.shot}`} />}</div><h3>{project.title}</h3><p>{project.text}</p><div className="tag-row">{project.tags.map((tag, tagIndex) => <span key={`${tag}-${tagIndex}`}>{tag}</span>)}</div><div className="project-links">{project.detailUrl && <a href={project.detailUrl} target="_blank" rel="noreferrer">{labels.learnMore} →</a>}{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer">{labels.liveSite} ↗</a>}</div></article>)}</div></section>
    <section id="profile" className="projects-section resume-section" style={{ order: 3 }}><div className="section-title-row"><h2>{display.homeHeadings.resume}</h2><Link href="/egitim">{labels.educationDetails} <b>→</b></Link></div><div className="resume-grid">{display.education.map((entry, index) => <article className="resume-card" key={`education-${index}`}><p className="resume-type">{labels.education}</p><h3>{entry.title}</h3><strong>{entry.organization}</strong><p>{entry.period}{entry.location ? ` · ${entry.location}` : ""}</p><small>{entry.description}</small><div className="tag-row">{entry.tags.map((tag, tagIndex) => <span key={`${tag}-${tagIndex}`}>{tag}</span>)}</div></article>)}{display.experience.map((entry, index) => <article className="resume-card" key={`experience-${index}`}><p className="resume-type">{labels.experience}</p><h3>{entry.title}</h3><strong>{entry.organization}</strong><p>{entry.period}{entry.location ? ` · ${entry.location}` : ""}</p><small>{entry.description}</small><div className="tag-row">{entry.tags.map((tag, tagIndex) => <span key={`${tag}-${tagIndex}`}>{tag}</span>)}</div>{entry.attachmentUrl && <small><a href={entry.attachmentUrl} target="_blank" rel="noreferrer">{entry.attachmentName || labels.viewDocument} ↗</a></small>}</article>)}</div></section>
    <section id="about" className="feature-grid" style={sectionStyle("features", 4)}><article id="skills" className="feature-card"><h2>{display.homeHeadings.skills}</h2><div className="skill-grid">{display.skills.map((skill, index) => <div key={`${skill}-${index}`}><b>{["⌁", "⌘", "▤", "◈", "✦"][index % 5]}</b><span>{skill}</span></div>)}</div><Link href="/yetenekler">{labels.viewSkills} <b>→</b></Link></article><article id="analysis" className="feature-card"><h2>{display.homeHeadings.methods}</h2><div className="method-grid">{display.methods.map((method, index) => <p key={`${method}-${index}`}><b>✓</b>{method}</p>)}</div><Link href="/sertifikalar">{labels.viewCertificates} <b>→</b></Link></article></section>
    <section className="projects-section compact-certificates" style={{ order: 5 }}><div className="section-title-row"><h2>{display.detailHeadings.certificates.kicker}</h2><Link href="/sertifikalar">{labels.viewCertificates} <b>→</b></Link></div><div className="certificate-strip">{display.certificates.map((certificate, index) => <article key={`home-certificate-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{certificate.title}</h3><p>{certificate.issuer}{certificate.date ? ` · ${certificate.date}` : ""}</p></div>{certificate.credentialUrl && <a href={certificate.credentialUrl} target="_blank" rel="noreferrer">↗</a>}</article>)}</div></section>
    <section className="contact-band" style={sectionStyle("contact", 6)}><div className="plane">⌁</div><p>{display.contactText}</p><Link className="outline-button" href="/iletisim">{labels.contactMe} <b>✉</b></Link></section>
    <footer id="contact" style={{ order: 7 }}><div><h2>{display.name}</h2><p>{display.tagline}</p></div><a href={`mailto:${display.email}`}>✉ &nbsp; {display.email}</a><a href={`tel:${display.phone.replace(/\s/g, "")}`}>⌕ &nbsp; {display.phone}</a><p>⌖ &nbsp; {display.city}</p><div className="socials"><a href={display.github} target="_blank" rel="noreferrer" aria-label="GitHub">◉</a><a href={display.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href={display.instagram} target="_blank" rel="noreferrer" aria-label="Instagram">◎</a></div></footer>
  </main>;
}
